import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

const root = new URL('../', import.meta.url);
const readJson = async (relativePath) => JSON.parse(await readFile(new URL(relativePath, root), 'utf8'));
const config = await readJson('seo.config.json');
const tours = {
  it: await readJson('public/data/it/tours.json'),
  pl: await readJson('public/data/pl/tours.json'),
};
const languages = ['it', 'pl'];
const escapeXml = (value) => String(value).replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;',
}[char]));
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[char]));
const basePath = (language) => language === 'it' ? '/it/tour' : '/pl/wycieczka';
const tourPath = (language, id) => `${basePath(language)}/${id}`;
const summarize = (value) => {
  if (value.length <= 155) return value;
  const excerpt = value.slice(0, 155);
  return `${excerpt.slice(0, excerpt.lastIndexOf(' ')).trimEnd()}…`;
};
const byId = Object.fromEntries(languages.map((language) => [
  language, new Map(tours[language].map((tour) => [tour.tour_id, tour])),
]));

for (const language of languages) {
  const ids = tours[language].map((tour) => tour.tour_id);
  if (ids.length !== new Set(ids).size || ids.some((id) => !/^[0-9]{3}$/.test(id))) {
    throw new Error(`Duplicate or invalid tour_id in ${language}/tours.json`);
  }
}
const itIds = [...byId.it.keys()];
if (itIds.length !== byId.pl.size || itIds.some((id) => !byId.pl.has(id))) {
  throw new Error('Tour IDs must exist in both languages for reciprocal hreflang.');
}

const entries = [];
for (const [key, translations] of Object.entries(config.pages)) {
  for (const language of languages) {
    const page = translations[language];
    entries.push({
      key: `${language}-${key}`,
      language,
      path: page.path,
      title: page.title,
      description: page.description,
      alternate: Object.fromEntries(languages.map((other) => [other, translations[other].path])),
      image: '/images/matemwe_beach_16x9.png',
    });
  }
}
for (const id of itIds) {
  for (const language of languages) {
    const tour = byId[language].get(id);
    entries.push({
      key: `${language}-tour-${id}`,
      language,
      path: tourPath(language, id),
      title: `${tour.title} | Zanzibar Vibe Tours`,
      description: summarize(tour.info),
      alternate: { it: tourPath('it', id), pl: tourPath('pl', id) },
      image: tour.img_title,
    });
  }
}

const uniquePaths = new Set(entries.map(({ path }) => path));
if (uniquePaths.size !== entries.length) throw new Error('Duplicate SEO route path.');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${entries.map((entry) => `  <url>\n    <loc>${escapeXml(config.origin + entry.path)}</loc>\n    <xhtml:link rel="alternate" hreflang="it" href="${escapeXml(config.origin + entry.alternate.it)}" />\n    <xhtml:link rel="alternate" hreflang="pl" href="${escapeXml(config.origin + entry.alternate.pl)}" />\n    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(config.origin + entry.alternate.it)}" />\n  </url>`).join('\n')}\n</urlset>\n`;

const rules = [
  '# Generated by scripts/generate-seo.mjs. Upload this file with dist.',
  'DirectoryIndex index.html',
  'ErrorDocument 404 /404.html',
  '<IfModule mod_rewrite.c>',
  '  RewriteEngine On',
  '  RewriteCond %{HTTPS} off',
  '  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]',
  '  RewriteCond %{THE_REQUEST} "\\s/+_pages/" [NC]',
  '  RewriteRule ^_pages/ - [R=404,L]',
];
for (const entry of entries) {
  const path = entry.path.replace(/^\//, '').replace(/\/$/, '');
  if (entry.path.endsWith('/')) rules.push(`  RewriteRule ^${path}$ /${path}/ [R=301,L]`);
  else rules.push(`  RewriteRule ^${path}/$ /${path} [R=301,L]`);
  rules.push(`  RewriteRule ^${path}/?$ /_pages/${entry.key}.html [L]`);
}
rules.push(
  '  RewriteCond %{REQUEST_FILENAME} !-f',
  '  RewriteCond %{REQUEST_FILENAME} !-d',
  '  RewriteRule ^ - [R=404,L]',
  '</IfModule>',
  '<IfModule mod_headers.c>',
  '  Header set X-Content-Type-Options "nosniff"',
  '  Header set X-Frame-Options "SAMEORIGIN"',
  '</IfModule>',
);
const htaccess = `${rules.join('\n')}\n`;

async function writeIfChanged(path, content) {
  let current;
  try { current = await readFile(path, 'utf8'); } catch { /* File is new. */ }
  if (current !== content) await writeFile(path, content, 'utf8');
}

const mode = process.argv[2];
if (mode === 'sitemap') {
  await writeIfChanged(new URL('public/sitemap.xml', root), sitemap);
  await writeIfChanged(new URL('public/.htaccess', root), htaccess);
} else if (mode === 'pages') {
  const dist = new URL('dist/', root);
  const template = await readFile(new URL('dist/index.html', root), 'utf8');
  const pageDirectory = new URL('dist/_pages/', root);
  await mkdir(pageDirectory, { recursive: true });

  const setTag = (html, selector, replacement) => {
    if (!html.includes(selector)) throw new Error(`Missing metadata tag ${selector}`);
    return html.replace(new RegExp(`<${selector}[^>]*>`), replacement);
  };

  for (const entry of entries) {
    const canonical = config.origin + entry.path;
    const alternate = entry.alternate;
    let html = template.replace(/<html lang="[^"]*">/, `<html lang="${entry.language}">`);
    html = html.replace(/<title>[^<]*<\/title>/, `<title>${escapeHtml(entry.title)}</title>`);
    html = setTag(html, 'meta name="description"', `<meta name="description" content="${escapeHtml(entry.description)}" />`);
    html = setTag(html, 'link rel="canonical"', `<link rel="canonical" href="${escapeHtml(canonical)}" />`);
    for (const language of [...languages, 'x-default']) {
      const path = language === 'x-default' ? alternate.it : alternate[language];
      html = setTag(html, `link rel="alternate" hreflang="${language}"`, `<link rel="alternate" hreflang="${language}" href="${escapeHtml(config.origin + path)}" />`);
    }
    html = setTag(html, 'meta property="og:title"', `<meta property="og:title" content="${escapeHtml(entry.title)}" />`);
    html = setTag(html, 'meta property="og:description"', `<meta property="og:description" content="${escapeHtml(entry.description)}" />`);
    html = setTag(html, 'meta property="og:locale"', `<meta property="og:locale" content="${entry.language === 'it' ? 'it_IT' : 'pl_PL'}" />`);
    html = setTag(html, 'meta property="og:locale:alternate"', `<meta property="og:locale:alternate" content="${entry.language === 'it' ? 'pl_PL' : 'it_IT'}" />`);
    html = html.replace('</head>', `    <meta property="og:url" content="${escapeHtml(canonical)}" />\n    <meta property="og:image" content="${escapeHtml(config.origin + entry.image)}" />\n    <meta name="twitter:card" content="summary_large_image" />\n    <meta name="twitter:title" content="${escapeHtml(entry.title)}" />\n    <meta name="twitter:description" content="${escapeHtml(entry.description)}" />\n    <meta name="twitter:image" content="${escapeHtml(config.origin + entry.image)}" />\n  </head>`);
    await writeFile(new URL(`dist/_pages/${entry.key}.html`, root), html, 'utf8');
  }

  const errorPage = template
    .replace(/<title>[^<]*<\/title>/, '<title>404 | Zanzibar Vibe Tours</title>')
    .replace(/<link rel="alternate" hreflang="[^"]+"[^>]*>\s*/g, '')
    .replace(/<link rel="canonical"[^>]*>\s*/g, '')
    .replace('</head>', '    <meta name="robots" content="noindex,follow" />\n  </head>');
  await writeFile(new URL('dist/404.html', root), errorPage, 'utf8');

  await writeFile(new URL('dist/.htaccess', root), htaccess, 'utf8');
  await writeFile(new URL('dist/sitemap.xml', root), sitemap, 'utf8');
  console.log(`Generated ${entries.length} SEO pages, sitemap and Apache routing in ${dist.pathname}`);
} else {
  throw new Error('Usage: node scripts/generate-seo.mjs sitemap|pages');
}
